### ISSUE TITLE
Can't get this to work...

### ISSUE THREAD

**Issue by mswanson** [jianyuan/onetab-export-to-json#3]
I am admittedly new to go so this is probably user error, but when I follow the README I get this after running `go get github.com/jianyuan/onetab-export-to-json`
```
$ onetab-export-to-json
zsh: command not found: onetab-export-to-json
```
I am on macOS and I installed go (version 1.14.15) via homebrew. Any help or suggestions on what I am doing wrong would be great. Thanks.

**Comment by jianyuan** [comment]
Try `go install github.com/jianyuan/onetab-export-to-json@latest`. It will compile and install the binary in `$GOPATH/bin`.
